[package]
name = "organ"
version = "0.1.0"
authors = ["Arnaud Castellanos Galea <poderosoarnaud@gmail.com>"]

[lib]
name = "organ"
crate-type = ["dylib"]

[dependencies]
arnaudio = { path = "arnaudio" }
