[package]
name = "arnaudio"
version = "0.1.0"
authors = ["Arnaud Castellanos Galea <poderosoarnaud@gmail.com>"]

[lib]
name = "arnaudio"

[dependencies]
gui = { path = "../gui" }
vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2.git" }

libc = "0.2"
